// TEST-ONLY ledger for Weather Voice personality content (#420).
// Built from docs/ai/tasks/ticket-420/issue-source.md and the owner-approved
// decisions (approved-prompt-v3.md). No production module may import this file.
// Statuses: retained | new (primary, 113 with retained) | active_supplemental
// (heavy_rain supplement, not primary) | retired | excluded (documentation only).
// `issueEn` is the issue-snapshot EN wording; `en` differs only where
// `enOverride` is true (three owner-approved overrides). `note` carries the
// caveat for the NOTE entries and for owner-activated restored reserves.
export const WEATHER_VOICE_LEDGER = Object.freeze([
  { id: "cold_01", condition: "cold", status: "retained", is: "Lopapeysan hafði rétt fyrir sér.", en: "The sweater was right.", issueEn: "The wool sweater was right.", enOverride: true, note: null },
  { id: "cold_02", condition: "cold", status: "retired", is: "Peysan fær framlengingu.", en: "The sweater gets an extension.", issueEn: "The sweater gets an extension.", enOverride: false, note: null },
  { id: "cold_03", condition: "cold", status: "retained", is: "Kaffið kólnar af samúð.", en: "The coffee cools out of sympathy.", issueEn: "Even the coffee is getting cold in sympathy.", enOverride: true, note: null },
  { id: "cold_04", condition: "cold", status: "new", is: "Þetta er bara hressandi.", en: "It's just refreshing.", issueEn: "It's just refreshing.", enOverride: false, note: "HOLD finding (Round 1): 'just refreshing' frames cold as pleasant; cold has no lower bound (Bible §3 test 5). Owner-activated 2026-10-03 (override, see Bible §14)." },
  { id: "cold_05", condition: "cold", status: "new", is: "Það er víst enginn kuldi.", en: "Apparently there's no such thing as cold.", issueEn: "Apparently there's no such thing as cold.", enOverride: false, note: "HOLD finding (Round 1): denies that cold exists; same bound problem (Bible §3 test 5). Owner-activated 2026-10-03 (override, see Bible §14)." },
  { id: "cold_06", condition: "cold", status: "new", is: "Bara spurning um að klæða sig.", en: "Apparently it's all about the clothing.", issueEn: "Apparently it's all about the clothing.", enOverride: false, note: "HOLD finding (Round 1): explains cold as a clothing matter; Bible §2 forbids teasing how the user dresses. Owner-activated 2026-10-03 (override, see Bible §14)." },
  { id: "cold_07", condition: "cold", status: "new", is: "Hitinn er með mjög hófleg markmið.", en: "The temperature has modest ambitions.", issueEn: "The temperature has modest ambitions.", enOverride: false, note: null },
  { id: "cold_08", condition: "cold", status: "new", is: "Þetta telst víst ferskt.", en: "Apparently this counts as fresh.", issueEn: "Apparently this counts as fresh.", enOverride: false, note: "RESERVE group 'fresh' (kept with cold_16 in Round 1). Owner-activated 2026-10-03." },
  { id: "cold_09", condition: "cold", status: "new", is: "Hitamælirinn er ekkert sérstaklega metnaðarfullur.", en: "The thermometer isn't feeling ambitious.", issueEn: "The thermometer isn't feeling ambitious.", enOverride: false, note: "RESERVE group 'thermometer' (kept with cold_07, cold_19 in Round 1). Owner-activated 2026-10-03." },
  { id: "cold_10", condition: "cold", status: "new", is: "Stuttbuxurnar fá frí.", en: "The shorts get the day off.", issueEn: "The shorts get the day off.", enOverride: false, note: "Understatement at tmax < 6 works only as irony; 'day off' matches the daily row." },
  { id: "cold_11", condition: "cold", status: "new", is: "Þetta er peysuveður.", en: "Sweater weather.", issueEn: "Sweater weather.", enOverride: false, note: "RESERVE group 'sweater / wool': cosy framing that evokes autumn (Bible §3). Owner-activated 2026-10-03." },
  { id: "cold_12", condition: "cold", status: "new", is: "Hitinn mætti ekki.", en: "The warmth didn't show up.", issueEn: "The warmth didn't show up.", enOverride: false, note: "Overlap group 'warmth is absent' (kept with cold_14, cold_21)." },
  { id: "cold_13", condition: "cold", status: "new", is: "Það er allavega ekki of heitt.", en: "At least it's not too warm.", issueEn: "At least it's not too warm.", enOverride: false, note: "HOLD finding (Round 1): 'at least not too warm' uses the consolation the issue retired in rain_heavy_01 (Bible §3 test 5). Owner-activated 2026-10-03 (override, see Bible §14)." },
  { id: "cold_14", condition: "cold", status: "new", is: "Hitinn fór eitthvað annað.", en: "The warmth went somewhere else.", issueEn: "The warmth went somewhere else.", enOverride: false, note: "Overlap group 'warmth is absent' (kept with cold_12, cold_21)." },
  { id: "cold_15", condition: "cold", status: "new", is: "Jæja. Ull.", en: "Well. Wool.", issueEn: "Well. Wool.", enOverride: false, note: null },
  { id: "cold_16", condition: "cold", status: "new", is: "Ferskt. Mjög ferskt.", en: "Fresh. Very fresh.", issueEn: "Fresh. Very fresh.", enOverride: false, note: null },
  { id: "cold_17", condition: "cold", status: "new", is: "Þetta er ein leið til að vakna.", en: "That's one way to wake up.", issueEn: "That's one way to wake up.", enOverride: false, note: "HOLD finding (Round 1): 'one way to wake up' infers morning / time of day (global rule). Owner-activated 2026-10-03 (override, see Bible §14)." },
  { id: "cold_18", condition: "cold", status: "new", is: "Hlýtt er afstætt hugtak.", en: "Warm is a relative term.", issueEn: "Warm is a relative term.", enOverride: false, note: "Understatement at tmax < 6; passes because it never says the cold is harmless." },
  { id: "cold_19", condition: "cold", status: "new", is: "Hitamælirinn heldur aftur af sér.", en: "The thermometer is holding back.", issueEn: "The thermometer is holding back.", enOverride: false, note: null },
  { id: "cold_20", condition: "cold", status: "new", is: "Ekki alveg hitabylgja.", en: "Not exactly a heatwave.", issueEn: "Not exactly a heatwave.", enOverride: false, note: "'Not exactly a heatwave' works only as irony." },
  { id: "cold_21", condition: "cold", status: "new", is: "Hitinn lætur lítið fyrir sér fara.", en: "The warmth is keeping a low profile.", issueEn: "The warmth is keeping a low profile.", enOverride: false, note: "Overlap group 'warmth is absent' (kept with cold_12, cold_14)." },
  { id: "cold_22", condition: "cold", status: "new", is: "Kuldinn mætti.", en: "The cold showed up.", issueEn: "The cold showed up.", enOverride: false, note: "Temporal idiom ('showed up'), not a time-of-day claim." },
  { id: "cold_23", condition: "cold", status: "new", is: "Það vantar nokkrar gráður.", en: "A few degrees appear to be missing.", issueEn: "A few degrees appear to be missing.", enOverride: false, note: "'A few degrees missing' works only as irony at tmax < 6." },
  { id: "cold_24", condition: "cold", status: "new", is: "Það er enginn kuldi, bara lélegur klæðnaður.", en: "There's no bad cold, only bad clothing.", issueEn: "There's no bad cold, only bad clothing.", enOverride: false, note: "HOLD finding (Round 1): 'no bad cold, only bad clothing' blames clothing (Bible §2). Owner-activated 2026-10-03 (override, see Bible §14)." },
  { id: "cold_wet_01", condition: "cold_wet", status: "retired", is: "Ullin fær að vinna fyrir kaupinu.", en: "The wool earns its keep.", issueEn: "The wool earns its keep.", enOverride: false, note: null },
  { id: "cold_wet_02", condition: "cold_wet", status: "retired", is: "Veðrið tók allan pakkann.", en: "The weather took the whole package.", issueEn: "The weather went for the full package.", enOverride: false, note: null },
  { id: "cold_wet_03", condition: "cold_wet", status: "retired", is: "Ekki alveg stuttbuxnaveður.", en: "Not quite shorts weather.", issueEn: "Not quite shorts weather.", enOverride: false, note: null },
  { id: "cold_wet_04", condition: "cold_wet", status: "excluded", is: "Kalt og blautt. Klassík.", en: "Cold and wet. Classic.", issueEn: "Cold and wet. Classic.", enOverride: false, note: null },
  { id: "cold_wet_05", condition: "cold_wet", status: "excluded", is: "Tveir fyrir einn.", en: "Two for one.", issueEn: "Two for one.", enOverride: false, note: null },
  { id: "cold_wet_06", condition: "cold_wet", status: "excluded", is: "Blautt var greinilega ekki nóg.", en: "Wet clearly wasn't enough.", issueEn: "Wet clearly wasn't enough.", enOverride: false, note: null },
  { id: "cold_wet_07", condition: "cold_wet", status: "excluded", is: "Kalt var greinilega ekki nóg.", en: "Cold clearly wasn't enough.", issueEn: "Cold clearly wasn't enough.", enOverride: false, note: null },
  { id: "cold_wet_08", condition: "cold_wet", status: "excluded", is: "Veðrið ákvað að klára dæmið.", en: "The weather decided to complete the set.", issueEn: "The weather decided to complete the set.", enOverride: false, note: null },
  { id: "cold_wet_09", condition: "cold_wet", status: "excluded", is: "Þetta er metnaðarfull óþægindi.", en: "This is ambitious discomfort.", issueEn: "This is ambitious discomfort.", enOverride: false, note: null },
  { id: "cold_wet_10", condition: "cold_wet", status: "excluded", is: "Bæði. Auðvitað.", en: "Both. Of course.", issueEn: "Both. Of course.", enOverride: false, note: null },
  { id: "cold_wet_11", condition: "cold_wet", status: "excluded", is: "Kuldinn fékk félagsskap.", en: "The cold got company.", issueEn: "The cold got company.", enOverride: false, note: null },
  { id: "cold_wet_12", condition: "cold_wet", status: "excluded", is: "Rigningin þurfti greinilega kælingu.", en: "Apparently the rain needed cooling.", issueEn: "Apparently the rain needed cooling.", enOverride: false, note: null },
  { id: "cold_wet_13", condition: "cold_wet", status: "excluded", is: "Vatn. Nú kaldara.", en: "Water. Now colder.", issueEn: "Water. Now colder.", enOverride: false, note: null },
  { id: "cold_wet_14", condition: "cold_wet", status: "excluded", is: "Þurrt og hlýtt var ekki í boði.", en: "Dry and warm wasn't on offer.", issueEn: "Dry and warm wasn't on offer.", enOverride: false, note: null },
  { id: "cold_wet_15", condition: "cold_wet", status: "excluded", is: "Veðrið valdi allan pakkann.", en: "The weather chose the full package.", issueEn: "The weather chose the full package.", enOverride: false, note: null },
  { id: "cold_wet_16", condition: "cold_wet", status: "excluded", is: "Kalt. Blautt. Næsta mál.", en: "Cold. Wet. Next.", issueEn: "Cold. Wet. Next.", enOverride: false, note: null },
  { id: "cold_wet_17", condition: "cold_wet", status: "excluded", is: "Hitinn fór. Rigningin varð eftir.", en: "The warmth left. The rain stayed.", issueEn: "The warmth left. The rain stayed.", enOverride: false, note: null },
  { id: "cold_wet_18", condition: "cold_wet", status: "excluded", is: "Þetta vinnur vel saman. Því miður.", en: "These work well together. Unfortunately.", issueEn: "These work well together. Unfortunately.", enOverride: false, note: null },
  { id: "cold_wet_19", condition: "cold_wet", status: "excluded", is: "Blaut kuldatilfinning. Frábær uppfinning.", en: "Wet cold. Wonderful invention.", issueEn: "Wet cold. Wonderful invention.", enOverride: false, note: null },
  { id: "cold_wet_20", condition: "cold_wet", status: "excluded", is: "Rigning með kælingu.", en: "Rain, now refrigerated.", issueEn: "Rain, now refrigerated.", enOverride: false, note: null },
  { id: "cold_wet_21", condition: "cold_wet", status: "excluded", is: "Kuldinn einn hefði alveg dugað.", en: "The cold alone would have been enough.", issueEn: "The cold alone would have been enough.", enOverride: false, note: null },
  { id: "cold_wet_22", condition: "cold_wet", status: "excluded", is: "Þetta er óþarflega blautt miðað við hitastig.", en: "This is unnecessarily wet for the temperature.", issueEn: "This is unnecessarily wet for the temperature.", enOverride: false, note: null },
  { id: "cold_wet_23", condition: "cold_wet", status: "excluded", is: "Veðrið er að leggja sig fram.", en: "The weather is really making an effort.", issueEn: "The weather is really making an effort.", enOverride: false, note: null },
  { id: "excellent_01", condition: "excellent", status: "retained", is: "Þetta er grunsamlega gott.", en: "This is suspiciously good.", issueEn: "This is suspiciously good.", enOverride: false, note: null },
  { id: "excellent_02", condition: "excellent", status: "retired", is: "Ekki segja neinum.", en: "Don't tell anyone.", issueEn: "Don't tell anyone.", enOverride: false, note: null },
  { id: "excellent_03", condition: "excellent", status: "retained", is: "Nú vantar bara kaffið.", en: "All that's missing is the coffee.", issueEn: "All that's missing is coffee.", enOverride: true, note: null },
  { id: "excellent_04", condition: "excellent", status: "new", is: "Þetta er útiveður.", en: "This is outdoor weather.", issueEn: "This is outdoor weather.", enOverride: false, note: null },
  { id: "excellent_05", condition: "excellent", status: "new", is: "Jæja. Þetta er óþægilega gott.", en: "Well. This is uncomfortably good.", issueEn: "Well. This is uncomfortably good.", enOverride: false, note: null },
  { id: "excellent_06", condition: "excellent", status: "new", is: "Ég var ekki undirbúinn fyrir þetta.", en: "I wasn't prepared for this.", issueEn: "I wasn't prepared for this.", enOverride: false, note: null },
  { id: "excellent_07", condition: "excellent", status: "new", is: "Eitthvað hlýtur að vera að.", en: "Something must be wrong.", issueEn: "Something must be wrong.", enOverride: false, note: "'Something must be wrong' can read as doubting the forecast data; in character." },
  { id: "excellent_08", condition: "excellent", status: "new", is: "Þetta þarf eiginlega ljósmyndasönnun.", en: "This almost requires photographic evidence.", issueEn: "This almost requires photographic evidence.", enOverride: false, note: null },
  { id: "excellent_09", condition: "excellent", status: "new", is: "Ég hef... ekkert að kvarta yfir.", en: "I have... nothing to complain about.", issueEn: "I have... nothing to complain about.", enOverride: false, note: null },
  { id: "excellent_10", condition: "excellent", status: "new", is: "Þetta gerist víst.", en: "Apparently this happens.", issueEn: "Apparently this happens.", enOverride: false, note: null },
  { id: "excellent_11", condition: "excellent", status: "new", is: "Ég ætla að láta þetta eiga sig.", en: "I'm leaving this one alone.", issueEn: "I'm leaving this one alone.", enOverride: false, note: null },
  { id: "excellent_12", condition: "excellent", status: "new", is: "Nei sko.", en: "Well, look at that.", issueEn: "Well, look at that.", enOverride: false, note: null },
  { id: "excellent_13", condition: "excellent", status: "new", is: "Þetta er eiginlega óþarfi.", en: "This is almost excessive.", issueEn: "This is almost excessive.", enOverride: false, note: null },
  { id: "excellent_14", condition: "excellent", status: "new", is: "Veðrið er að sýna sig.", en: "The weather is showing off.", issueEn: "The weather is showing off.", enOverride: false, note: null },
  { id: "excellent_15", condition: "excellent", status: "new", is: "Ég kann ekki alveg við þetta.", en: "I'm not entirely comfortable with this.", issueEn: "I'm not entirely comfortable with this.", enOverride: false, note: null },
  { id: "excellent_16", condition: "excellent", status: "new", is: "Hver pantaði þetta?", en: "Who ordered this?", issueEn: "Who ordered this?", enOverride: false, note: null },
  { id: "excellent_17", condition: "excellent", status: "new", is: "Þetta er ekki mjög íslenskt.", en: "This isn't very Icelandic.", issueEn: "This isn't very Icelandic.", enOverride: false, note: null },
  { id: "excellent_18", condition: "excellent", status: "new", is: "Ég athugaði tvisvar.", en: "I checked twice.", issueEn: "I checked twice.", enOverride: false, note: "'I checked twice' can read as doubting the forecast data; in character." },
  { id: "excellent_19", condition: "excellent", status: "new", is: "Þetta er gott. Grunsamlega gott.", en: "This is good. Suspiciously good.", issueEn: "This is good. Suspiciously good.", enOverride: false, note: "RESERVE finding (Round 1): near-duplicate of excellent_01 with one word added. Owner-activated 2026-10-03." },
  { id: "excellent_20", condition: "excellent", status: "new", is: "Ég er orðlaus. Næstum því.", en: "I'm speechless. Almost.", issueEn: "I'm speechless. Almost.", enOverride: false, note: null },
  { id: "excellent_21", condition: "excellent", status: "new", is: "Allt í lagi. Þetta er frábært.", en: "Fine. This is excellent.", issueEn: "Fine. This is excellent.", enOverride: false, note: "Nearest to hype; the 'Fine.' opener keeps it begrudging." },
  { id: "excellent_22", condition: "excellent", status: "new", is: "Ég ætla ekki að spyrja spurninga.", en: "I'm not asking questions.", issueEn: "I'm not asking questions.", enOverride: false, note: null },
  { id: "excellent_23", condition: "excellent", status: "new", is: "Svona á víst að gera þetta.", en: "Apparently this is how it's done.", issueEn: "Apparently this is how it's done.", enOverride: false, note: null },
  { id: "good_01", condition: "good", status: "retained", is: "Þetta má alveg.", en: "This'll do.", issueEn: "This'll do.", enOverride: false, note: null },
  { id: "good_02", condition: "good", status: "retained", is: "Jæja. Þetta er bara gott.", en: "Well. This is just good.", issueEn: "Well. This is just good.", enOverride: false, note: null },
  { id: "good_03", condition: "good", status: "retained", is: "Engin kvörtun að sinni.", en: "No complaints for now.", issueEn: "No complaints for now.", enOverride: false, note: null },
  { id: "good_04", condition: "good", status: "new", is: "Ég finn ekkert að þessu.", en: "I can't find anything wrong with this.", issueEn: "I can't find anything wrong with this.", enOverride: false, note: null },
  { id: "good_05", condition: "good", status: "new", is: "Veðrið hagar sér.", en: "The weather is behaving.", issueEn: "The weather is behaving.", enOverride: false, note: null },
  { id: "good_06", condition: "good", status: "new", is: "Það hefur verið verra.", en: "It's been worse.", issueEn: "It's been worse.", enOverride: false, note: "Idiomatic 'It's been worse' refers to past or other weather generically." },
  { id: "good_07", condition: "good", status: "new", is: "Ég samþykki þetta.", en: "I approve.", issueEn: "I approve.", enOverride: false, note: null },
  { id: "good_08", condition: "good", status: "new", is: "Engin ástæða til dramatíkur.", en: "No need for drama.", issueEn: "No need for drama.", enOverride: false, note: "'No need for drama' can be read as a mild instruction; it still comments on the weather." },
  { id: "good_09", condition: "good", status: "new", is: "Þetta er furðulega eðlilegt.", en: "This is strangely normal.", issueEn: "This is strangely normal.", enOverride: false, note: null },
  { id: "good_10", condition: "good", status: "new", is: "Ég ætla ekki að eyðileggja þetta með kvörtunum.", en: "I'm not ruining this with complaints.", issueEn: "I'm not ruining this with complaints.", enOverride: false, note: null },
  { id: "good_11", condition: "good", status: "new", is: "Þetta stenst skoðun.", en: "This passes inspection.", issueEn: "This passes inspection.", enOverride: false, note: null },
  { id: "good_12", condition: "good", status: "new", is: "Jæja. Engin gild afsökun.", en: "Well. No valid complaints.", issueEn: "Well. No valid complaints.", enOverride: false, note: "HOLD finding (Round 1): IS 'afsökun' vs EN 'complaints'; overlaps good_03 and good_04. Owner-activated 2026-10-03 (override, see Bible §14)." },
  { id: "good_13", condition: "good", status: "new", is: "Ég hafði áhyggjur að óþörfu.", en: "Apparently I worried for nothing.", issueEn: "Apparently I worried for nothing.", enOverride: false, note: null },
  { id: "good_14", condition: "good", status: "new", is: "Veðrið kom undirbúið.", en: "The weather came prepared.", issueEn: "The weather came prepared.", enOverride: false, note: "Temporal idiom ('came prepared'), not a time-of-day claim." },
  { id: "good_15", condition: "good", status: "new", is: "Ég get unnið með þetta.", en: "I can work with this.", issueEn: "I can work with this.", enOverride: false, note: null },
  { id: "good_16", condition: "good", status: "new", is: "Þetta verður ekki mikið betra án þess að verða grunsamlegt.", en: "Much better than this would be suspicious.", issueEn: "Much better than this would be suspicious.", enOverride: false, note: "Longest IS line (10 words, 59 characters). Owner may trim; not trimmed here. Layout-test priority ID." },
  { id: "good_17", condition: "good", status: "new", is: "Ég ætla bara að njóta þessa í hljóði.", en: "I'll just quietly appreciate this.", issueEn: "I'll just quietly appreciate this.", enOverride: false, note: null },
  { id: "good_18", condition: "good", status: "new", is: "Ekkert vesen. Skrítið.", en: "No trouble. Strange.", issueEn: "No trouble. Strange.", enOverride: false, note: null },
  { id: "good_19", condition: "good", status: "new", is: "Þetta er næstum því fullorðinslegt veður.", en: "This is almost responsible weather.", issueEn: "This is almost responsible weather.", enOverride: false, note: null },
  { id: "good_20", condition: "good", status: "new", is: "Íslenska veðrið gleymdi sér.", en: "Icelandic weather forgot itself for a moment.", issueEn: "Icelandic weather forgot itself for a moment.", enOverride: false, note: "'Forgot itself' is generic. EN adds 'for a moment', which the IS does not say; harmless." },
  { id: "good_21", condition: "good", status: "new", is: "Allt í lagi. Þú vinnur.", en: "Fine. You win.", issueEn: "Fine. You win.", enOverride: false, note: "'You win' may read as addressed to the user on a standalone card or share image. Issue explicitly approves it as addressed to the weather. Residual ambiguity documented, not resolved." },
  { id: "good_22", condition: "good", status: "new", is: "Ég var tilbúinn að kvarta.", en: "I was ready to complain.", issueEn: "I was ready to complain.", enOverride: false, note: null },
  { id: "good_23", condition: "good", status: "new", is: "Þetta er eiginlega bara fínt.", en: "This is actually quite nice.", issueEn: "This is actually quite nice.", enOverride: false, note: "Close to good_02 ('just good' vs 'actually quite nice'); both are issue tone examples. Kept." },
  { id: "rain_01", condition: "rain", status: "retained", is: "Það fylgir vatn með.", en: "Comes with water.", issueEn: "Comes with water.", enOverride: false, note: null },
  { id: "rain_02", condition: "rain", status: "retained", is: "Regnjakki með aðalhlutverk.", en: "Rain jacket, starring role.", issueEn: "Rain jacket, starring role.", enOverride: false, note: null },
  { id: "rain_03", condition: "rain", status: "new", is: "Vatn. Að ofan.", en: "Water. From above.", issueEn: "Water. From above.", enOverride: false, note: null },
  { id: "rain_04", condition: "rain", status: "new", is: "Já já. Rigning.", en: "Yes, yes. Rain.", issueEn: "Yes, yes. Rain.", enOverride: false, note: null },
  { id: "rain_05", condition: "rain", status: "new", is: "Auðvitað.", en: "Of course.", issueEn: "Of course.", enOverride: false, note: null },
  { id: "rain_06", condition: "rain", status: "new", is: "Þurrt fær frí í dag.", en: "Dry has the day off.", issueEn: "Dry has the day off.", enOverride: false, note: "Scheduling metaphor ('day off'); matches the daily row." },
  { id: "rain_07", condition: "rain", status: "new", is: "Himinninn lekur.", en: "The sky is leaking.", issueEn: "The sky is leaking.", enOverride: false, note: null },
  { id: "rain_08", condition: "rain", status: "new", is: "Þetta þurfti greinilega að vera blautt.", en: "Apparently this needed to be wet.", issueEn: "Apparently this needed to be wet.", enOverride: false, note: null },
  { id: "rain_09", condition: "rain", status: "new", is: "Veðrið valdi vatn.", en: "The weather chose water.", issueEn: "The weather chose water.", enOverride: false, note: null },
  { id: "rain_10", condition: "rain", status: "new", is: "Rigningin mætti á réttum tíma. Eins og alltaf.", en: "The rain arrived right on time. As always.", issueEn: "The rain arrived right on time. As always.", enOverride: false, note: "HOLD finding (Round 1): 'right on time, as always' claims a schedule the engine cannot know. Owner-activated 2026-10-03 (override, see Bible §14)." },
  { id: "rain_11", condition: "rain", status: "new", is: "Þurrkur var greinilega ekki á dagskrá.", en: "Dry clearly wasn't on the agenda.", issueEn: "Dry clearly wasn't on the agenda.", enOverride: false, note: "RESERVE group 'dry is unavailable' (shares the scheduling metaphor with rain_06). Owner-activated 2026-10-03." },
  { id: "rain_12", condition: "rain", status: "new", is: "Vatnsheldur er fallegt orð.", en: "Waterproof is a beautiful word.", issueEn: "Waterproof is a beautiful word.", enOverride: false, note: null },
  { id: "rain_13", condition: "rain", status: "new", is: "Þetta er mjög íslenskt.", en: "Very Icelandic.", issueEn: "Very Icelandic.", enOverride: false, note: null },
  { id: "rain_14", condition: "rain", status: "new", is: "Regnið er komið. Það fannst öllum vanta.", en: "The rain is here. Apparently it was missed.", issueEn: "The rain is here. Apparently it was missed.", enOverride: false, note: "'The rain is here' asserts arrival; EN passive softens the IS. Idiomatic; owner may reword." },
  { id: "rain_15", condition: "rain", status: "new", is: "Nú er allt aðeins blautara.", en: "Everything is slightly wetter now.", issueEn: "Everything is slightly wetter now.", enOverride: false, note: "HOLD finding (Round 1): 'everything is slightly wetter now' claims a change; the engine is daily-scope. Owner-activated 2026-10-03 (override, see Bible §14)." },
  { id: "rain_16", condition: "rain", status: "new", is: "Himinninn er í þvottaham.", en: "The sky is on wash cycle.", issueEn: "The sky is on wash cycle.", enOverride: false, note: null },
  { id: "rain_17", condition: "rain", status: "new", is: "Rigningin hefur tekið vaktina.", en: "Rain has taken the shift.", issueEn: "Rain has taken the shift.", enOverride: false, note: null },
  { id: "rain_18", condition: "rain", status: "new", is: "Það þurfti víst að vökva.", en: "Apparently something needed watering.", issueEn: "Apparently something needed watering.", enOverride: false, note: "Overlap group 'rain was needed' (kept with rain_08 and rain_23)." },
  { id: "rain_19", condition: "rain", status: "new", is: "Veðrið fór blautu leiðina.", en: "The weather took the wet route.", issueEn: "The weather took the wet route.", enOverride: false, note: "RESERVE group 'weather chose water' (same structure as rain_09). Owner-activated 2026-10-03." },
  { id: "rain_20", condition: "rain", status: "new", is: "Þurrt hefði verið of einfalt.", en: "Dry would have been too simple.", issueEn: "Dry would have been too simple.", enOverride: false, note: null },
  { id: "rain_21", condition: "rain", status: "new", is: "Rigning. Klassískt.", en: "Rain. Classic.", issueEn: "Rain. Classic.", enOverride: false, note: null },
  { id: "rain_22", condition: "rain", status: "new", is: "Skýin eru greinilega með verkefni.", en: "The clouds clearly have a job to do.", issueEn: "The clouds clearly have a job to do.", enOverride: false, note: null },
  { id: "rain_23", condition: "rain", status: "new", is: "Þetta er víst gott fyrir gróðurinn.", en: "Apparently it's good for the plants.", issueEn: "Apparently it's good for the plants.", enOverride: false, note: null },
  { id: "rain_heavy_01", condition: "heavy_rain", status: "retired", is: "Bíllinn fær allavega þvott.", en: "At least the car gets a wash.", issueEn: "At least the car gets a wash.", enOverride: false, note: null },
  { id: "rain_heavy_02", condition: "heavy_rain", status: "retired", is: "Þurrt er afstætt hugtak.", en: "Dry is a relative concept.", issueEn: "Dry is a relative concept.", enOverride: false, note: null },
  { id: "rain_heavy_03", condition: "heavy_rain", status: "retired", is: "Þetta er fullmikill áhugi á vatni.", en: "This is an excessive interest in water.", issueEn: "This is an excessive interest in water.", enOverride: false, note: null },
  { id: "rain_heavy_04", condition: "heavy_rain", status: "excluded", is: "Þetta er orðið töluvert af vatni.", en: "That's becoming quite a lot of water.", issueEn: "That's becoming quite a lot of water.", enOverride: false, note: null },
  { id: "rain_heavy_05", condition: "heavy_rain", status: "excluded", is: "Himinninn er greinilega ekki að spara.", en: "The sky clearly isn't holding back.", issueEn: "The sky clearly isn't holding back.", enOverride: false, note: null },
  { id: "rain_heavy_06", condition: "heavy_rain", status: "excluded", is: "Rigningin tók þetta alvarlega.", en: "The rain took this seriously.", issueEn: "The rain took this seriously.", enOverride: false, note: null },
  { id: "rain_heavy_07", condition: "heavy_rain", status: "excluded", is: "Vatnið er komið í aðalhlutverk.", en: "Water has taken the starring role.", issueEn: "Water has taken the starring role.", enOverride: false, note: null },
  { id: "rain_heavy_08", condition: "heavy_rain", status: "excluded", is: "Þetta er meira en smá væta.", en: "This is more than a little damp.", issueEn: "This is more than a little damp.", enOverride: false, note: null },
  { id: "rain_heavy_09", condition: "heavy_rain", status: "excluded", is: "Skýin eru að tæma lagerinn.", en: "The clouds are clearing out the inventory.", issueEn: "The clouds are clearing out the inventory.", enOverride: false, note: null },
  { id: "rain_heavy_10", condition: "heavy_rain", status: "excluded", is: "Það er nóg af vatni í boði.", en: "There's plenty of water on offer.", issueEn: "There's plenty of water on offer.", enOverride: false, note: null },
  { id: "rain_heavy_11", condition: "heavy_rain", status: "excluded", is: "Rigningin hefur tekið yfir.", en: "The rain has taken over.", issueEn: "The rain has taken over.", enOverride: false, note: null },
  { id: "rain_heavy_12", condition: "heavy_rain", status: "excluded", is: "Þurrt er ekki orðið sem kemur upp í hugann.", en: "Dry isn't the word that comes to mind.", issueEn: "Dry isn't the word that comes to mind.", enOverride: false, note: null },
  { id: "rain_heavy_13", condition: "heavy_rain", status: "excluded", is: "Himinninn opnaði kranann.", en: "The sky opened the tap.", issueEn: "The sky opened the tap.", enOverride: false, note: null },
  { id: "rain_heavy_14", condition: "heavy_rain", status: "excluded", is: "Þetta er metnaðarfull rigning.", en: "This is ambitious rain.", issueEn: "This is ambitious rain.", enOverride: false, note: null },
  { id: "rain_heavy_15", condition: "heavy_rain", status: "excluded", is: "Rigningin ætlar greinilega að klára þetta.", en: "The rain clearly intends to finish the job.", issueEn: "The rain clearly intends to finish the job.", enOverride: false, note: null },
  { id: "rain_heavy_16", condition: "heavy_rain", status: "excluded", is: "Vatn. Töluvert af því.", en: "Water. Quite a lot of it.", issueEn: "Water. Quite a lot of it.", enOverride: false, note: null },
  { id: "rain_heavy_17", condition: "heavy_rain", status: "excluded", is: "Skýin eru með dagskrá.", en: "The clouds have an agenda.", issueEn: "The clouds have an agenda.", enOverride: false, note: null },
  { id: "rain_heavy_18", condition: "heavy_rain", status: "excluded", is: "Þetta er orðið persónulegt.", en: "This is getting personal.", issueEn: "This is getting personal.", enOverride: false, note: null },
  { id: "rain_heavy_19", condition: "heavy_rain", status: "excluded", is: "Rigningin er ekkert að hálfkáka.", en: "The rain isn't doing things by halves.", issueEn: "The rain isn't doing things by halves.", enOverride: false, note: null },
  { id: "rain_heavy_20", condition: "heavy_rain", status: "excluded", is: "Það er enginn skortur á úrkomu.", en: "No shortage of precipitation.", issueEn: "No shortage of precipitation.", enOverride: false, note: null },
  { id: "rain_heavy_21", condition: "heavy_rain", status: "excluded", is: "Himinninn hefur gefið sig.", en: "The sky has given way.", issueEn: "The sky has given way.", enOverride: false, note: null },
  { id: "rain_heavy_22", condition: "heavy_rain", status: "excluded", is: "Þetta telst ekki lengur nokkrir dropar.", en: "This no longer qualifies as a few drops.", issueEn: "This no longer qualifies as a few drops.", enOverride: false, note: null },
  { id: "rain_heavy_23", condition: "heavy_rain", status: "excluded", is: "Jæja. Meira vatn.", en: "Well. More water.", issueEn: "Well. More water.", enOverride: false, note: null },
  { id: "rain_heavy_24", condition: "heavy_rain", status: "active_supplemental", is: "Er ekki kominn tími á örkina?", en: "Is it time for the ark yet?", issueEn: "Is it time for the ark yet?", enOverride: false, note: null },
  { id: "rain_heavy_25", condition: "heavy_rain", status: "active_supplemental", is: "Örkin hlýtur að vera í smíðum.", en: "The ark must be under construction.", issueEn: "The ark must be under construction.", enOverride: false, note: null },
  { id: "rain_heavy_26", condition: "heavy_rain", status: "excluded", is: "Það mætti fara að huga að örkinni.", en: "Might be time to start thinking about the ark.", issueEn: "Might be time to start thinking about the ark.", enOverride: false, note: null },
  { id: "rain_heavy_27", condition: "heavy_rain", status: "excluded", is: "Nói hafði kannski punkt.", en: "Noah may have had a point.", issueEn: "Noah may have had a point.", enOverride: false, note: null },
  { id: "rain_heavy_28", condition: "heavy_rain", status: "excluded", is: "Þetta er farið að kalla á örk.", en: "This is starting to call for an ark.", issueEn: "This is starting to call for an ark.", enOverride: false, note: null },
  { id: "rain_heavy_29", condition: "heavy_rain", status: "active_supplemental", is: "Hvar er Nói þegar maður þarf á honum að halda?", en: "Where's Noah when you need him?", issueEn: "Where's Noah when you need him?", enOverride: false, note: null },
  { id: "sun_wind_01", condition: "sun_wind", status: "retained", is: "Sólin mætir. Lognið ekki.", en: "The sun showed up. The calm didn't.", issueEn: "The sun showed up. The calm didn't.", enOverride: false, note: null },
  { id: "sun_wind_02", condition: "sun_wind", status: "retained", is: "Bjart yfir. Hárið á hlið.", en: "Bright skies. Hair sideways.", issueEn: "Bright skies. Hair sideways.", enOverride: false, note: null },
  { id: "sun_wind_03", condition: "sun_wind", status: "new", is: "Sólin kom. Vindurinn líka.", en: "The sun came. So did the wind.", issueEn: "The sun came. So did the wind.", enOverride: false, note: "Temporal idiom ('came'); same idiom as released sun_wind_01. Overlap group kept." },
  { id: "sun_wind_04", condition: "sun_wind", status: "new", is: "Bjart og blásið.", en: "Bright and breezy.", issueEn: "Bright and breezy.", enOverride: false, note: "'Bright and breezy' is a stock phrase, slightly benign for 5-10 m/s. Owner approved the IS and EN lines unchanged (2026-10-03)." },
  { id: "sun_wind_05", condition: "sun_wind", status: "new", is: "Sólin gerir sitt. Vindurinn líka.", en: "The sun is doing its thing. So is the wind.", issueEn: "The sun is doing its thing. So is the wind.", enOverride: false, note: "RESERVE group 'sun arrives' (near-duplicate of sun_wind_03). Owner-activated 2026-10-03." },
  { id: "sun_wind_06", condition: "sun_wind", status: "new", is: "Fallegt. Með mótvindi.", en: "Beautiful. With a headwind.", issueEn: "Beautiful. With a headwind.", enOverride: false, note: "HOLD finding (Round 1): 'with a headwind' states a direction the engine does not know. Owner-activated 2026-10-03 (override, see Bible §14)." },
  { id: "sun_wind_07", condition: "sun_wind", status: "new", is: "Sólin lofar góðu. Vindurinn hefur aðrar hugmyndir.", en: "The sun looks promising. The wind has other ideas.", issueEn: "The sun looks promising. The wind has other ideas.", enOverride: false, note: null },
  { id: "sun_wind_08", condition: "sun_wind", status: "new", is: "Bjart yfir. Rólegt, síður.", en: "Bright skies. Calm, less so.", issueEn: "Bright skies. Calm, less so.", enOverride: false, note: "RESERVE group 'bright but not calm' (EN 'Calm, less so' is awkward). Owner-activated 2026-10-03." },
  { id: "sun_wind_09", condition: "sun_wind", status: "new", is: "Sólin er saklaus af þessu.", en: "The sun is innocent in all this.", issueEn: "The sun is innocent in all this.", enOverride: false, note: null },
  { id: "sun_wind_10", condition: "sun_wind", status: "new", is: "Vindurinn lætur sólina ekki eiga sviðið.", en: "The wind won't let the sun have the stage.", issueEn: "The wind won't let the sun have the stage.", enOverride: false, note: null },
  { id: "sun_wind_11", condition: "sun_wind", status: "new", is: "Sól með aukahljóðum.", en: "Sunshine with sound effects.", issueEn: "Sunshine with sound effects.", enOverride: false, note: null },
  { id: "sun_wind_12", condition: "sun_wind", status: "new", is: "Bjart. En ekki beint kyrrt.", en: "Bright. Not exactly still.", issueEn: "Bright. Not exactly still.", enOverride: false, note: null },
  { id: "sun_wind_13", condition: "sun_wind", status: "new", is: "Sólin mætti ekki ein.", en: "The sun didn't come alone.", issueEn: "The sun didn't come alone.", enOverride: false, note: "RESERVE group 'sun arrives' (same beat as sun_wind_03, rephrased). Owner-activated 2026-10-03." },
  { id: "sun_wind_14", condition: "sun_wind", status: "new", is: "Fallegt úr fjarlægð.", en: "Looks lovely from a distance.", issueEn: "Looks lovely from a distance.", enOverride: false, note: "'Lovely from a distance' implies the reader is indoors; figurative." },
  { id: "sun_wind_15", condition: "sun_wind", status: "new", is: "Sól og vindur. Klassískt samstarf.", en: "Sun and wind. A classic partnership.", issueEn: "Sun and wind. A classic partnership.", enOverride: false, note: null },
  { id: "sun_wind_16", condition: "sun_wind", status: "new", is: "Veðrið gat ekki bara verið gott.", en: "The weather couldn't just be nice.", issueEn: "The weather couldn't just be nice.", enOverride: false, note: null },
  { id: "sun_wind_17", condition: "sun_wind", status: "new", is: "Sólin reynir.", en: "The sun is trying.", issueEn: "The sun is trying.", enOverride: false, note: "'The sun is trying' suggests the sun struggles on a clear day; figurative." },
  { id: "sun_wind_18", condition: "sun_wind", status: "new", is: "Bjartviðri með fyrirvara.", en: "Clear skies, with conditions attached.", issueEn: "Clear skies, with conditions attached.", enOverride: false, note: null },
  { id: "sun_wind_19", condition: "sun_wind", status: "new", is: "Sólskin. Með smá mótþróa.", en: "Sunshine. With some resistance.", issueEn: "Sunshine. With some resistance.", enOverride: false, note: null },
  { id: "sun_wind_20", condition: "sun_wind", status: "new", is: "Vindurinn vill líka athygli.", en: "The wind wants attention too.", issueEn: "The wind wants attention too.", enOverride: false, note: null },
  { id: "sun_wind_21", condition: "sun_wind", status: "new", is: "Sól að ofan. Vindur frá hlið.", en: "Sun above. Wind from the side.", issueEn: "Sun above. Wind from the side.", enOverride: false, note: "HOLD finding (Round 1): 'wind from the side' states a direction the engine does not know. Owner-activated 2026-10-03 (override, see Bible §14)." },
  { id: "sun_wind_22", condition: "sun_wind", status: "new", is: "Næstum því fullkomið.", en: "Almost perfect.", issueEn: "Almost perfect.", enOverride: false, note: "HOLD finding (Round 1): 'almost perfect' overstates comfort and blurs with good/excellent. Owner-activated 2026-10-03 (override, see Bible §14)." },
  { id: "wind_extreme_01", condition: "extreme_wind", status: "retired", is: "Vindur: Já.", en: "Wind: Yes.", issueEn: null, enOverride: false, note: null },
  { id: "wind_extreme_02", condition: "extreme_wind", status: "retired", is: "Ég tek þetta sem persónulega árás.", en: "I take this as a personal attack.", issueEn: null, enOverride: false, note: null },
  { id: "wind_extreme_03", condition: "extreme_wind", status: "retired", is: "Nei.", en: "No.", issueEn: null, enOverride: false, note: null },
  { id: "wind_extreme_04", condition: "extreme_wind", status: "retired", is: "Vindurinn hefur orðið.", en: "The wind has become a whole thing.", issueEn: null, enOverride: false, note: null },
  { id: "wind_extreme_05", condition: "extreme_wind", status: "retired", is: "Þetta var ekki í bæklingnum.", en: "This wasn't in the brochure.", issueEn: null, enOverride: false, note: null },
  { id: "wind_strong_01", condition: "strong_wind", status: "retired", is: "Lognið á frí.", en: "Calm is on vacation.", issueEn: "Calm is on vacation.", enOverride: false, note: null },
  { id: "wind_strong_02", condition: "strong_wind", status: "retired", is: "Hárið hefur gefist upp.", en: "The hair has given up.", issueEn: "The hair has given up.", enOverride: false, note: null },
  { id: "wind_strong_03", condition: "strong_wind", status: "retired", is: "Það blæs ekki af þessu.", en: "This isn't blowing over.", issueEn: "This isn't blowing over.", enOverride: false, note: null },
  { id: "wind_strong_04", condition: "strong_wind", status: "excluded", is: "Vindurinn hefur skoðanir.", en: "The wind has opinions.", issueEn: "The wind has opinions.", enOverride: false, note: null },
  { id: "wind_strong_05", condition: "strong_wind", status: "excluded", is: "Lognið kemur greinilega ekki.", en: "Calm clearly isn't coming.", issueEn: "Calm clearly isn't coming.", enOverride: false, note: null },
  { id: "wind_strong_06", condition: "strong_wind", status: "excluded", is: "Það er hreyfing á loftinu.", en: "There's some movement in the air.", issueEn: "There's some movement in the air.", enOverride: false, note: null },
  { id: "wind_strong_07", condition: "strong_wind", status: "excluded", is: "Vindurinn lætur vita af sér.", en: "The wind is making itself known.", issueEn: "The wind is making itself known.", enOverride: false, note: null },
  { id: "wind_strong_08", condition: "strong_wind", status: "excluded", is: "Þetta er orðið töluvert af lofti.", en: "That's becoming quite a lot of air.", issueEn: "That's becoming quite a lot of air.", enOverride: false, note: null },
  { id: "wind_strong_09", condition: "strong_wind", status: "excluded", is: "Loftið er á ferðinni.", en: "The air is on the move.", issueEn: "The air is on the move.", enOverride: false, note: null },
  { id: "wind_strong_10", condition: "strong_wind", status: "excluded", is: "Vindurinn tók aðeins of mikið pláss.", en: "The wind is taking up a little too much space.", issueEn: "The wind is taking up a little too much space.", enOverride: false, note: null },
  { id: "wind_strong_11", condition: "strong_wind", status: "excluded", is: "Það er ekkert feimið við þennan vind.", en: "This wind isn't shy.", issueEn: "This wind isn't shy.", enOverride: false, note: null },
  { id: "wind_strong_12", condition: "strong_wind", status: "excluded", is: "Vindurinn er kominn í aðalhlutverk.", en: "The wind has taken the starring role.", issueEn: "The wind has taken the starring role.", enOverride: false, note: null },
  { id: "wind_strong_13", condition: "strong_wind", status: "excluded", is: "Logn var greinilega ekki í boði.", en: "Calm clearly wasn't on offer.", issueEn: "Calm clearly wasn't on offer.", enOverride: false, note: null },
  { id: "wind_strong_14", condition: "strong_wind", status: "excluded", is: "Vindurinn hefur tekið vaktina.", en: "The wind has taken the shift.", issueEn: "The wind has taken the shift.", enOverride: false, note: null },
  { id: "wind_strong_15", condition: "strong_wind", status: "excluded", is: "Þetta er meira en léttur andvari.", en: "This is more than a light breeze.", issueEn: "This is more than a light breeze.", enOverride: false, note: null },
  { id: "wind_strong_16", condition: "strong_wind", status: "excluded", is: "Loftið er með læti.", en: "The air is making a scene.", issueEn: "The air is making a scene.", enOverride: false, note: null },
  { id: "wind_strong_17", condition: "strong_wind", status: "excluded", is: "Vindurinn mætir af fullum krafti.", en: "The wind showed up in force.", issueEn: "The wind showed up in force.", enOverride: false, note: null },
  { id: "wind_strong_18", condition: "strong_wind", status: "excluded", is: "Þetta blæs aðeins meira en kurteislegt er.", en: "This is windier than strictly polite.", issueEn: "This is windier than strictly polite.", enOverride: false, note: null },
  { id: "wind_strong_19", condition: "strong_wind", status: "excluded", is: "Vindurinn er greinilega með dagskrá.", en: "The wind clearly has an agenda.", issueEn: "The wind clearly has an agenda.", enOverride: false, note: null },
  { id: "wind_strong_20", condition: "strong_wind", status: "excluded", is: "Það er nóg af vindi fyrir alla.", en: "There's enough wind for everyone.", issueEn: "There's enough wind for everyone.", enOverride: false, note: null },
  { id: "wind_strong_21", condition: "strong_wind", status: "excluded", is: "Vindurinn þarf greinilega athygli.", en: "The wind clearly needs attention.", issueEn: "The wind clearly needs attention.", enOverride: false, note: null },
  { id: "wind_strong_22", condition: "strong_wind", status: "excluded", is: "Loftið gat ekki bara verið kyrrt.", en: "The air couldn't just stay still.", issueEn: "The air couldn't just stay still.", enOverride: false, note: null },
  { id: "wind_strong_23", condition: "strong_wind", status: "excluded", is: "Jæja. Vindur.", en: "Well. Wind.", issueEn: "Well. Wind.", enOverride: false, note: null },
]);

export const WEATHER_VOICE_SAFETY_LEDGER = Object.freeze([
  {
    "message_id": "safety_extreme_wind",
    "condition": "extreme_wind",
    "voice_level": "serious",
    "text_is": "Mjög hvassviðri er í spánni. Aðstæður geta verið varasamar. Athugaðu opinberar veðurviðvaranir áður en þú leggur af stað.",
    "text_en": "Very strong winds are forecast. Conditions may be hazardous. Check official weather warnings before setting out."
  },
  {
    "message_id": "safety_strong_wind",
    "condition": "strong_wind",
    "voice_level": "cautious",
    "text_is": "Hvassviðri er í spánni. Skoðaðu aðstæður vel áður en þú ákveður næsta áfangastað.",
    "text_en": "Strong winds are forecast. Check conditions carefully before choosing your next destination."
  },
  {
    "message_id": "safety_heavy_rain",
    "condition": "heavy_rain",
    "voice_level": "cautious",
    "text_is": "Mikil rigning er í spánni. Það gæti þurft að endurskoða planið.",
    "text_en": "Heavy rain is forecast. You may need to reconsider your plans."
  },
  {
    "message_id": "safety_cold_wet",
    "condition": "cold_wet",
    "voice_level": "cautious",
    "text_is": "Kalt og blautt er í spánni. Taktu mið af því þegar þú skipuleggur daginn.",
    "text_en": "Cold and wet conditions are forecast. Take this into account when planning your day."
  }
]);
