export const WEATHER_MAP = {
  0: { icon: "☀️", text: "Clear sky" },
  1: { icon: "🌤️", text: "Mainly clear" },
  2: { icon: "⛅", text: "Partly cloudy" },
  3: { icon: "☁️", text: "Overcast" },
  45: { icon: "🌫️", text: "Fog" },
  48: { icon: "🌫️", text: "Rime fog" },
  51: { icon: "🌦️", text: "Light drizzle" },
  53: { icon: "🌦️", text: "Drizzle" },
  55: { icon: "🌦️", text: "Heavy drizzle" },
  61: { icon: "🌧️", text: "Light rain" },
  63: { icon: "🌧️", text: "Rain" },
  65: { icon: "🌧️", text: "Heavy rain" },
  66: { icon: "🌨️", text: "Freezing rain" },
  67: { icon: "🌨️", text: "Heavy freezing rain" },
  71: { icon: "🌨️", text: "Light snow" },
  73: { icon: "🌨️", text: "Snow" },
  75: { icon: "❄️", text: "Heavy snow" },
  77: { icon: "🌨️", text: "Snow grains" },
  80: { icon: "🌦️", text: "Showers" },
  81: { icon: "🌧️", text: "Heavy showers" },
  82: { icon: "🌧️", text: "Violent showers" },
  95: { icon: "⛈️", text: "Thunderstorm" },
  96: { icon: "⛈️", text: "Thunder + hail" },
  99: { icon: "⛈️", text: "Severe thunder + hail" },
};
